version: "3.9"
services:
  nom_servei:
    image: mariadb:latest
    container_name: mariadb_volum
    environment:
      MARIADB_ROOT_PASSWORD: 1234
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - 3319:3306
volumes:
  mariadb_data: